# Generated by Django 4.1 on 2022-10-01 23:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCombustivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=9)),
                ('ano', models.IntegerField()),
                ('tanque', models.IntegerField()),
                ('odometro', models.FloatField()),
                ('renavam', models.CharField(max_length=11)),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carro.tipocombustivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Troca_Oleo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('km_atual', models.FloatField()),
                ('proxima_troca', models.FloatField()),
                ('filtro_oleo', models.BooleanField(default=True)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carro.veiculo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('odometro', models.FloatField()),
                ('data', models.CharField(max_length=10)),
                ('local', models.CharField(max_length=50)),
                ('observacao', models.CharField(blank=True, max_length=144)),
                ('opcao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carro.tipodespesa')),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carro.veiculo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Abastecer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=10)),
                ('odometro', models.FloatField()),
                ('qtd_litros', models.FloatField()),
                ('completo', models.BooleanField(default=False)),
                ('preco', models.FloatField()),
                ('valor_total', models.FloatField()),
                ('posto', models.CharField(max_length=20)),
                ('placa', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carro.veiculo')),
                ('tipo_combustivel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carro.tipocombustivel')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
